### PR TITLE
Fix issue where an mdns record with no target will cause the wrong device to be selected

### LINKED ISSUE #104: Target changes to BETAFPV 900 TX when clicking SELECT under Network Devices
## Expected Behavior

Not really sure actually.

## Current Behavior

With the new DNS device detection, my RX (Happymodel EP1) shows up under Network Devices. When I click SELECT, the device category is changed to BETAFPV 900 MHZ and the target to BETAFPV 900 TX.

## Steps to Reproduce

1. Select Hapymodel EP1 RX target with previously configured home wifi SSID and password

2. Choose WIFI Flashing Method

3. RX shows up under Network Devices

4. Click SELECT and see that the target has changed

## Your Environment

- Operating System and version: Windows 10, Configurator version 1.2.1
- RX hardware: Happymodel EP1 running master from a few weeks ago

### PR DESCRIPTION
**Pull request by justinlampley**
Closes #104

### CODE REVIEW

File: src/ui/views/ConfiguratorView/index.tsx [hunk 1]
```diff
@@ -677,27 +677,48 @@ const ConfiguratorView: FunctionComponent<ConfiguratorViewProps> = (props) => {
       if (dnsDevice) {
         const targetName = dnsDevice.target.toUpperCase();
 
-        const device = deviceTargets?.find((item) => {
+        // if targetName is an empty string, then return
+        if (targetName.trim().length === 0) {
+          return;
```
Comment (jurgelenas) [inline src/ui/views/ConfiguratorView/index.tsx:682]: What will happen when user select this target? Nothing? If so, I think feedback should be visible to the user somehow. For example an error message could be displayed, same thing for other cases where you just return from the callback.

**Review by jurgelenas — CHANGES_REQUESTED** [review]

File: src/ui/views/ConfiguratorView/index.tsx (hunk 1 above)
Comment (jurgelenas) [reply src/ui/views/ConfiguratorView/index.tsx:682]: Another option for case where target is just empty - "Select" button could be hidden for example
